
import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import AmbientBackground from "@/components/AmbientBackground";
import Providers from "@/components/Providers";


const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CV Dekho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${spaceGrotesk.variable} antialiased`}>

        <Providers> {/* ✅ THIS is the fix */}
          <div className="relative">

  {/* Background */}
  <AmbientBackground />

  {/* Content */}
  <div className="relative z-10">
    {children}
  </div>
  </div>
        </Providers>
</body>
    </html>
    
  );
}